=== macc704/TurtleCafe/turtlecafe2/smartdoc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from index.xml by XMLBuddy -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ELEMENT body (section+)>
<!ELEMENT console (#PCDATA)>
<!ATTLIST console title NMTOKEN #REQUIRED>
<!ELEMENT dd (#PCDATA|p)*>
<!ELEMENT dl (dd|dt)*>
<!ELEMENT doc (head,body)>
<!ATTLIST doc xml:lang NMTOKEN #REQUIRED>
<!ELEMENT dt (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT head (title)>
<!ELEMENT li (#PCDATA)>
<!ELEMENT native (#PCDATA)>
<!ATTLIST native format NMTOKEN #REQUIRED>
<!ELEMENT note (#PCDATA)>
<!ELEMENT p (#PCDATA|a|em|note|program)*>
<!ELEMENT program (#PCDATA)>
<!ATTLIST program
	encoding NMTOKEN #IMPLIED
	id NMTOKEN #IMPLIED
	javasrcSyntaxHilight NMTOKEN #IMPLIED
	normalizer CDATA #IMPLIED
	src CDATA #IMPLIED
	title NMTOKEN #IMPLIED
>
<!ELEMENT section (p|subsection|ul)*>
<!ATTLIST section title NMTOKEN #REQUIRED>
<!ATTLIST section id NMTOKEN #IMPLIED>
<!ELEMENT subsection (console|native|p|program|subsubsection|text.turtle.applet)*>
<!ATTLIST subsection title NMTOKEN #REQUIRED>
<!ELEMENT subsubsection (dl|p|program)*>
<!ATTLIST subsubsection title NMTOKEN #REQUIRED>
<!ELEMENT text.turtle.applet EMPTY>
<!ATTLIST text.turtle.applet
	chapter CDATA #REQUIRED
	class NMTOKEN #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ul (li)>

=== macc704/TurtleCafe/turtlecafe2/introduction_ronproeditor/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "introduction_ronproeditor">
]>

<doc xml:lang='ja'>
	<head>
		<title>論プロエディタでJavaプログラムを動かしてみよう</title>
	</head>

	<body>
		<p>
			論プロエディタを使ったJavaタートルグラフィックスのプログラムの開発環境を整備しましょう。
		</p>
		<p>
			テキストエディタを使って実行環境を整備することもできますが、
			ここでは、初心者向けのエディタ「論プロエディタ」を使う方法を解説します。
		</p>

		<section title="学習目標">
			<p>
				<ul>
					<li>論プロエディタを使い、自分のコンピュータでサンプルプログラム（HelloWorld.java）が動かせるようになる</li>
				</ul>
			</p>
		</section>
		
		<section title="環境のインストール">
			<section title="JDKのインストール">
				<p>
					JDK(Java SE Development Kit)とは、Java開発環境のことです。
					自分のPCでJavaを開発するためには、JDKをインストールする必要があります。
					（あらかじめインストールされているJREでは、Javaを動かすことは出来ますが、Javaのプログラムを作ることは出来ません）
				</p>
	
				<section title="JDKがインストールされているか調べる">
					<p>コマンドプロンプト（「Windows」＞「プログラム」＞「アクセサリ」の中にあります）を開いて、次のコマンドを打ってください</p>
					<console title="JDKの確認">
javac -version
					</console>
					<p>version 6以上(7でもOK)が入っているかどうか確認してください。</p>		
				</section>
			
				<section title="JDKのインストール">
					<p>JDK6以上をインストールします。</p>		
					<p>	
						JDKは現在、Oracle社が開発・配布しています。						
						<a href="http://www.oracle.com/technetwork/java/javase/downloads/jdk-6u27-download-440405.html">ここ</a>
						からダウンロードし、インストールを行ってください。
						(静大学内の場合、\\fs\share\class\2011プログラミング社会\　からコピーできるようにしました．)				
					</p>
					<p>							
						インストールが終わったら、環境変数の設定をします。
						配布された資料に従って､設定を行ってください。
						（又は<a href="http://mail2.nara-edu.ac.jp/~asait/java/java_install/java_install.htm">ここ</a>のサイトなどが
						参考になります。）
					</p>
					<p>							
						環境変数の設定が終わったら、コマンドプロンプトを開き、「JDKがインストールされているか調べる」で説明した方法で、
						コマンドが実行できるかどうか確認してください。
					</p>
				</section>
			</section>
				
			<section title="論プロエディタのインストール">
				<p>Javaの初心者向けエディタ「論プロエディタ」をダウンロードしよう。</p>
				<p>インストールは、フォルダをデスクトップに解凍するだけです。</p>
				<p>
					<a
						href="https://ce.cs.inf.shizuoka.ac.jp/fs/smb/pub/ronproeditor/">
						ここ
					</a>
					から、もっとも新しいバージョン（数字が一番大きいもの）をダウンロードすること。
					(静大学内の場合、\\fs\share\class\2011プログラミング社会\　からコピーできるようにしました．)
				</p>				
			</section>
		</section>
		
		<section title="論プロエディタの基本的な使い方">

			<section title="論プロエディタの基本">
				<section title="起動の仕方">
					<p>
						論プロエディタフォルダの中の「RonproEditor.jar」をダブルクリックすると起動できます。
					</p>
					<p>起動画面は以下のようになります</p>
					<figure id="fig:RonproEditor" title="起動画面"
						src="image/RonproEditor" style="scale:1.0" />
				</section>

				<section title="各部名称・機能">
					<p>各部の名称と機能は以下の通りです</p>
					<figure id="fig:RonproEditorName" title="起動画面"
						src="image/RonproEditorName" style="scale:1.0" />
					<dl>
						<dt>リソースビューワ</dt>
						<dd>
							<a href="#sec:resource">リソース</a>のツリーを表示します。
							プロジェクトをクリックすると展開し、所属しているクラスが表示されます。
						</dd>
						<dt>エディタ</dt>
						<dd><a href="#sec:programmingprocess">ソースコード</a>を編集するためのエディタ</dd>
						<dt>コンソール</dt>
						<dd>
							コンパイル、実行したときに標準入出力につながれます。
							Macのターミナル、Winのコマンドプロンプトに相当するものです。
							<a href="#part:extra">論プロエディタを使わない場合</a>はこれらで代用できます。
							コンパイル、実行したときに当該プログラムの文字情報の入出力が行われ、
							コンパイル時には<a href="#sec:compileerror">エラーが出力</a>されます。
							実行時には当該プログラムが必要とする文字情報の入出力が行われます。
							表示されている文字情報は、コンパイルするたびにクリアされます。
						</dd>
					</dl>
				</section>

				<section title="リソース" id="resource">
					<p>
						リソースとは、論プロエディタで使用するデータのことです。
						基本的には、<a href="#sec:class">クラス</a>のことです。
					</p>
					<p>
						クラスをまとめられると使いやすい（回別に分けないとごちゃごちゃになる）ので、
						プロジェクトを用意しています。プロジェクトは、クラスをまとめておくものです。
					</p>
					<dl>
						<dt>プロジェクト</dt>
						<dd>
							プロジェクトとは、プログラムを入れておくフォルダのようなものです。この授業では、
							「Kougi07」など、授業ごとにプロジェクトを作るものとします。
						</dd>
						<dt>クラス（ファイル）</dt>
						<dd>
							クラスとは、Javaのプログラムの単位のことです。
							Javaでは、原則的に１つのクラスは１つのファイルに書かれるため、
							論プロエディタではクラスとファイルをまとめてクラス（ファイル）とし、ひとつの単位として扱っています。
						</dd>
					</dl>
					<fyi title="プロジェクトとクラス（ファイル）を作ろう">
						<p>
							まず、論プロエディタの「File」メニューから「NewProject」を選んで「kougi07」というプロジェクトを作ろう。
						</p>
						<p>
							次に、論プロエディタの「File」メニューから「NewClass(File)」を選び、「Turtle」テンプレートを選んで、「HelloWorld」というクラスを作ろう。
						</p>
					</fyi>
					<p>
						これで、「Kougi07」プロジェクトの中に、「HelloWorld.java」というファイルが作成された。
					</p>
					<figure id="fig:HelloWorld"
						title="HelloWorld.java作成完了画面" src="image/HelloWorld"
						style="scale:1.0" />
				</section>
			</section>

			<section title="プログラム作成の流れ" id="programmingprocess">
				<p>Javaプログラムを作成して実行するには、次のようなプロセスをたどることになります。</p>

				<figure id="fig:process" title="Javaプログラム作成のプロセス"
					src="image/process" style="scale:1.0" />

				<dl>
					<dt>ソースコード</dt>
					<dd>プログラムが書かれたテキストファイルのこと</dd>
					<dt>バイトコード</dt>
					<dd>プログラムをコンピュータが実行できる形式に変換したもの</dd>
					<dt>コンパイル</dt>
					<dd>ソースコードをバイトコードに変換すること</dd>
				</dl>

				<section title="プログラムの編集">
					<p>それでは、先ほど作った「HelloWorld.java」を編集してみよう。</p>
					<p>以下のプログラムと同じプログラムを打ち込んでみよう。</p>
					<figure id="fig:helloworldsource"
						title="HelloWorldソースコード" src="image/HelloWorldSource"
						style="scale:1.0" />
				</section>
				<section title="コンパイル">

					<p>次に、ソースコード（HelloWorld.java）をコンパイルしてみよう。</p>
					<p>論プロエディタの「Java」メニューから「Compile」を選ぼう。</p>
					<p>コンパイルが成功すると、このような表示がコンソールに出ます。</p>

					<figure id="fig:consolecompile" title="コンパイル"
						src="image/ConsoleCompile" style="scale:1.0" />
					<p>
						プロジェクトの中で初めてタートルプログラムをコンパイルしたときに、
						「注」という赤い警告のメッセージが出ますが、
						プログラムは問題なくコンパイルされているので、心配しなくて大丈夫です。
					</p>
					<p>
						（Javaは5.0から新しい文法が用意され、その文法に従っていないものには
						警告が出るようになりました。タートルライブラリは98年に作られたもので、
						一部に古いJavaの文法を使っているため、このような警告メッセージが出ます。）
					</p>
					<p>
						<b>プログラムにミスがあると、コンパイルは成功しません。</b>
						詳しくは<a href="#sec:compileerror">２章の「コンパイルエラー」</a> を参考にしてください。
					</p>
				</section>

				<section title="実行">

					<p>次に、プログラムを実行しよう。「Java」メニューから「Run」を選ぼう。</p>
					<p>コンソールに「HelloWorld!」が出ていれば成功です。</p>

					<figure id="fig:consolerun" title="コンパイル"
						src="image/ConsoleRun" style="scale:1.0" />
					<p>
						無限ループするプログラムを書いてしまった、など、プログラムが止まらなくなることがあります。
						そのような場合は、Javaメニューにある「Kill（実行強制停止）」を使ってプログラムを止めること。
					</p>
				</section>

				<fyi title="やってみよう！">
					<p>
						「print("Hello World!");」の次の行に「fd(100);」と書いて、コンパイル、実行してみよう。
					</p>
					<p>下のボタンと同じ結果が得られれば成功です。</p>
				<text.turtle.applet.nodownload class="HelloTurtle" chapter="&CHAPTER;" />					
				</fyi>
			</section>

		</section>

		<section title="発展的な使い方">


			<section title="サンプルプログラムの使い方">
				<section title="サンプルプログラムの使い方">
					<p>
						サンプルプログラム「House.java」を
						<a href="introduction_cns/src/House.java">
							ここ
						</a>
						からダウンロードし、
						論プロエディタフォルダの中にある「MyProjects」フォルダの中の「Kougi07」フォルダに保存しよう。
					</p>
					<p>
						論プロエディタの画面で「F5」を押すと、表示が更新されて「Kougi07」プロジェクトの中にHouse.javaが表示されます。
						House.javaをダブルクリックすると、エディタにプログラムが表示されます。
					</p>
					<p>
						「F5」を押してリソースビューワを更新しないとクラス（ファイル）が表示されないので、
						サンプルプログラムをダウンロードして「MyProjects」フォルダに追加したら、必ず「F5」を押すこと。
					</p>
					<figure id="fig:HouseDownloaded"
						title="House.javaを論プロエディタで読み込んだ様子" src="image/HouseDownloaded"
						style="scale:1.0" />

					<fyi title="やってみよう！">
						<p>
							サンプルプログラムをコンパイルし、実行してみよう。
							次のボタンと同じ結果が得られれば、成功です。
						</p>
						<text.turtle.applet.nodownload class="House" chapter="&CHAPTER;" />	
					</fyi>
				</section>
				<section title="リソースとファイルシステムの関係">
					<p>
						論プロエディタの「プロジェクト」と「クラス（ファイル）」の２つのリソースは、
						ファイルシステム（MacやWindowsの通常の画面）ではそれぞれ「フォルダ」と「ファイル」に対応します。
					</p>
					<p>
						プロジェクト「Kougi07」は、論プロエディタフォルダの中の「MyProjects」フォルダの中の「Kougi07」フォルダに対応します。
					</p>
					<p>
						クラス（ファイル）「HelloWorld.java」は、Kougi07」フォルダの中の「HelloWorld.java」に対応します。
					</p>
					<p>
						論プロエディタで作ったプロジェクトやクラス（ファイル）は、ファイルシステムで見ることができるし、
						ファイルシステムで作ったフォルダやファイルを論プロエディタで読み込むこともできます。
					</p>
				</section>
			</section>

			<!-- 
			<section title="自分のPCでJavaと論プロエディタを使う方法">
				<p>
					大学のPCではなく、自分のPCでJavaを使うためには、JDKをインストールする必要があります（大学のPCには、あらかじめインストールされている）。
				</p>
				<p>
					JDK(Java SE Development Kit)とは、Java開発環境のことです。JDKのインストールについては、
					<a
						href="introduction_cns/html/JDK_install.html">
						ここ（Mac・Windows両方のやり方が書いてあります）
					</a>
					を参考にするとよい。
				</p>
				<p>
					JDKをインストールした後に、論プロエディタをインストールしてください。
					論プロエディタのインストール以降の操作は、MacでもWindowsでも、大学のPCでの操作と変わりません。
				</p>
			</section>
			 -->

			<section title="その他の機能">
				<p>
					論プロエディタのその他の機能を紹介します。
					<dl>
						<dt>Rename</dt>
						<dd>リソースの名前を変更できる。</dd>
						<dt>Delete</dt>
						<dd>リソースを削除できる</dd>
						<dt>Refresh</dt>
						<dd>
							リソースビューワを更新できる。 サンプルプログラムをダウンロードしたときなど、
							ファイルシステムからファイルやフォルダを追加したときに使う。
						</dd>
						<dt>Undo（やり直し）</dt>
						<dd>作業をひとつ前の状態に戻すことができる。</dd>
						<dt>Redo（やり直しのキャンセル）</dt>
						<dd>直前のUndoを取り消して、Undoする前の状態に戻すことができる。</dd>
						<dt>Format</dt>
						<dd>プログラムを整形し、見やすくする。 括弧の対応の確認などに役立つ。</dd>
						<dt>Kill</dt>
						<dd>
							現在実行している（複数実行している場合、すべての）プログラムを
							強制的に停止することが出来る。無限ループのプログラムを書いてしまったとき
							など、プログラムが止まらなくなってしまったときに、役立つ。
						</dd>
					</dl>
				</p>
			</section>
			<section title="ショートカットキー">
				<p>
					論プロエディタは、ほとんどのコマンドをショートカットで実行できるように作られています。
					ショートカットキーを使ってコマンドを実行したいときは、メニューの右に表示されているキーを同時押ししてください。
					（例：コンパイル（Ctrl+E）→「Ctrl」キーと「E」キーを同時に押す）
				</p>
				<p>
					ショートカットキーは覚えやすいように、 編集にかかわるコマンドのショートカットは左下（ZXCV）に、
					Javaにかかわるコマンドのショートカットは左上（WSER）に集中しています。
				</p>

				<figure id="fig:shortcutkey" title="ショートカットキー"
						src="image/keyboard" style="scale:1.0" />
				<p>（http://www2d.biglobe.ne.jp/~msyk/index.htmlの「キーボード配列案」のフリー画像をお借りしました。）</p>
			</section>
		</section>
	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/introduction_win/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "introduction_win">
]>

<doc xml:lang='ja'>
	<head>
		<title>Windows標準環境でJavaプログラムを動かしてみよう</title>
	</head>

	<body>
		<p>
			論プロエディタは教育用に設計されたエディタです．
			Windows環境＋テキストエディタでのJavaタートルグラフィックスのプログラム実行環境を整備しましょう。
		</p>

		<section title="目標">
			<ul>
				<li>自分の環境でタートルプログラムを動かすこと</li>
			</ul>
		</section>

		<section title="プログラム作成・実行の準備">

			<section title="Java開発環境(JDK)のインストール">
				<p>Javaの開発元であるSunが配布しているJavaキット。普通のコンピュータには入っていない。</p>
				<p>インストールは、「JDK インストール」とgoogleで検索し、出てきた手順に従うこと</p>
			</section>

			<section title="作業用フォルダの作成">
				<p>任意のフォルダを作業用フォルダとできる。</p>
				<p>このテキストでは、「マイドキュメント」に「myjava」というフォルダを作成することを想定する。</p>
			</section>

			<section title="タートルプログラムのダウンロード">
				<p>
					タートルを動かすために必要なプログラムをダウンロードする。
					以下のリンクを右クリックして、今作ったフォルダに保存する。
				</p>
				<p>
					(「対象をファイルに保存」を選択して、ダイアログから今作ったフォルダを選ぶ)
				</p>
				<ul>
					<li><a href="&CHAPTER;/src/Turtle.java">Turtle.java</a></li>
				</ul>

			</section>

			<section title="サンプルプログラムのダウンロード">
				<p>
					同様の方法で、家を書くサンプルプログラムをダウンロードし、同じ場所に保存する。
				</p>
				<ul>
					<li><a href="&CHAPTER;/src/House.java">House.java</a></li>
				</ul>
			</section>

			<section title="テキストエディタの整備">
				<p>
					必要なものはテキストエディタだけである。有料のソフトは使う必要ない。
					テキストエディタなら、なんでもよい（メモ帳でもプログラムは書ける）。
				</p>
				<p>
					心に決めたものがない人は「xyzzy」を使おう。
				</p>
			</section>

		</section>

		<section title="プログラムの作成と実行">

			<p>
				Javaプログラムを作成して実行するには、次のようなプロセスをたどることになる。
			</p>

			<figure
						id="fig:process"
						title="Javaプログラム作成のプロセス"
						src="image/process" style="scale:1.0"  />

			<dl>
				<dt>ソースコード</dt>
				<dd>プログラムが書かれたテキストファイルのこと</dd>
				<dt>バイトコード</dt>
				<dd>プログラムをコンピュータが実行できる形式に変換したもの</dd>
				<dt>コンパイル</dt>
				<dd>ソースコードをバイトコードに変換すること</dd>
			</dl>

			<section title="プログラム(ソースコード)の作成">

				<p>
					テキストエディタの準備ができたら、ダウンロードしたHouse.javaをテキストエディタで開いてみよう。
				</p>

				<p>
					次のようなプログラムが出てくるはずである。
				</p>

				<program title="House.java"
					id="src:house"
					src="src/House.java"
					normalizer="line, javasrc" javasrcSyntaxHilight="true"
					encoding="Shift_JIS"/>

				<p>
					導入編では、実行してみるのが目標だから、まだ意味が分からなくてよいし、いじらなくてよい（書き換えてはいけない）。
				</p>

			</section>

			<section title="コマンドプロンプトを利用したプログラムの実行">

				<p>
					プログラムをコンパイルして実行するには、コマンドプロンプトから命令する必要がある。
					「スタート」「プログラム」から「コマンドプロンプト」を起動する。
				</p>

				<p>
					今回使うコマンドは次のとおり。
				</p>

				<ul>
					<li>
						<p>今いるフォルダにあるファイル一覧を見る。</p>
					</li>
					<console title="ファイル一覧を見る">
dir
					</console>

					<li>
						<p>フォルダを移動する。
							<note>フォルダ階層を一つ上がる(戻る)には、「cd ..」を使う。</note>
						</p>
					</li>
					<console title="フォルダを移動する">
cd [移動するフォルダ名]
					</console>

					<li>
						<p>ドライブを移動する。</p>
					</li>
					<console title="フォルダを移動する">
[ドライブ名]:
					</console>

					<li>
						<p>javaソースプログラムをコンパイルする。</p>
					</li>
					<console title="コンパイルする">
javac *.java
					</console>

					<li>
						<p>タートルプログラムを実行する。</p>
					</li>
					<console title="実行する">
java -cp . Turtle [クラス名]
					</console>
				</ul>
			</section>

			<section title="コンパイル">

				<p>
					先ほど作ったフォルダに移動してみよう。
				</p>

				<p>
					プログラムを始める時は、必ずこのフォルダに移動しなければならないので注意。
					（dirと打ってみよう。Turtle.java と House.java が出てくれば成功）。
				</p>

				<p>
					コンパイルしてみよう。
				</p>

				<console title="コンパイル">
javac *.java
				</console>

				<p>
					次のプロンプトが帰ってくるまでは、コンパイル中である。
					エラーが出なければ、コンパイル成功。
				</p>

				<p>
					コンパイルに成功したら、もう一度 dir と打ってみよう。
					Turtle.class と House.class が出来れば成功している。
				</p>

			</section>

			<section title="実行">

				<p>
					javaコマンドを使って実行してみよう（こんどは .java がいらないので注意）。
				</p>

				<console title="実行">
java -cp . Turtle House
				</console>

				<p>
					次のような画面が出れば成功である。おめでとう。
				</p>

				<figure
						id="fig:turtle"
						title="実行画面"
						src="image/turtle" style="scale:1.0"  />
				<p>
					終了する場合は、FileからQuitを選ぶ。
				</p>
			</section>

		</section>

	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/appendix_soundlib/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "appendix_soundlib">
]>

<doc xml:lang='ja'>

	<head>
		<title>音を鳴らしてみよう</title>
	</head>

	<body>
		<section title="音を鳴らす方法">
			<p>BSoundライブラリを使うと、MP3、WAVE、MIDI形式のファイルを制御して、音を鳴らすことができます。</p>
			<p>BSoundライブラリをプログラム内で利用するためには、プログラムの行頭に次の1行を加えます。</p>
			<program>
import blib.sound.BSound;
			</program>

			<p>MP3、WAVE、MIDI以外のファイルを鳴らしたい場合は、<a href="http://media-convert.com/ja/" target="_blank">変換サイト</a>で対応できるファイル形式に変換してください。</p>
		</section>

		<section title="BSoundの使い方">
			<section title="BGMを鳴らす場合">
				<p>BGMなど再生時間が長い音を鳴らす場合は、まず再生するファイルを指定して、BSound オブジェクトを作成します。</p>

				<program>
BSound bgm = new BSound("bgm.mp3"); //BSoundオブジェクトを作成する
				</program>

				<p>そして、作成したBSoundオブジェクトに対して、play() や stop() などの命令を行います。</p>

				<program>
bgm.play(); //BGMを再生する
				</program>
			</section>

			<section title="効果音を鳴らす場合">
				<p>効果音など再生時間が短い音を鳴らす場合は、BGMと同じ方法でも鳴らすことができますが、次のような簡易的な命令を使うこともできます。</p>

				<program>
BSound.play("fire.wav");
				</program>

				<p>また、次のように音量を指定して再生することもできます。</p>

				<program>
BSound.play("fire.wav", 100); //効果音を再生する
				</program>

				<p>ただし、上記2つの簡易的な命令で音を再生した場合、その音を途中で停止したり、音量を変更したりすることができません。</p>
			</section>

			<section title="あらかじめ音を読み込んでおく">
				<p>音の再生時に反応速度が重要な場合は、あらかじめ音を読み込んでおくこと、再生するまでの反応速度を早くすることができます。</p>

				<program>
BSound.load("fire.wav"); // あらかじめ効果音を読み込んでおく
BSound.play("fire.wav"); // 効果音を再生する
				</program>

				<p>ただし、再生時間が長い大きなファイルを読み込む場合は、それだけメモリが必要になります。</p>
			</section>
		</section>

		<section title="BSoundで利用できる命令">
			<section title="再生と停止">
				<dl>
					<dt>play()</dt>
					<dd>
						音を1度だけ再生します。
					</dd>

					<dt>loop()</dt>
					<dd>
						音をループ再生します。音の再生が終わると、もう一度はじめから再生します。
						stop()が呼ばれるまで再生し続けます。
					</dd>

					<dt>stop()</dt>
					<dd>
						音を停止します。
					</dd>

					<dt>isPlaying()</dt>
					<dd>
						音が再生中かどうか調べます。必ず、if文の条件文の中に書いて下さい。
					</dd>
				</dl>
			</section>

			<section title ="音量の取得・変更">
				<dl>
					<dt>getVolume()</dt>
					<dd>
						音量を取得します。取得する音量は0(消音)から100(最大音量)のいずれかです。
					</dd>

					<dt>setVolume(??)</dt>
					<dd>
						音量を??に設定します。設定できる音量は0(消音)から100(最大音量)までです。
					</dd>

					<dt>getDefaultVolume()</dt>
					<dd>
						初期設定の音量を取得します。取得する音量は0(消音)から100(最大音量)のいずれかです。
					</dd>

					※midiファイルの音量は常に100です(音量調整はできません)。
				</dl>
			</section>

			<section title ="簡易再生">
				<dl>
					<dt>BSound.play(??)</dt>
					<dd>
						指定した音ファイルを再生します。効果音など再生時間が短いファイルを再生する場合に最適です。
						ただし、この方法で再生した音は途中で停止したり、音量を変更したりすることはできません。
					</dd>

					<dt>BSound.play(??, ??)</dt>
					<dd>
						1番目の引数で指定した音ファイルを、2番目の引数で指定した音量(0-100)で再生します。
						効果音など再生時間が短いファイルを再生する場合に最適です。
						ただし、この方法で再生した音は途中で停止したり、音量を変更したりすることはできません。
					</dd>
				</dl>
			</section>

			<section title ="音の読み込み">
				<dl>
					<dt>BSound.load(??)</dt>
					<dd>
						指定した音ファイルを読み込みます。
						ファイルを読み込んだ場合、反応速度が早くなりますが、ファイルを読み込むためのメモリ領域が必要です。
					</dd>

				</dl>
			</section>
		</section>

		<section title="練習問題">
			<section title="問題1：シューティングゲームに効果音をつけよう">
				<p>11章の最後にあるシューティングゲームを改良して、効果音をつけましょう。</p>
				<p>次の2つの場合において、好きな音を鳴らして下さい。</p>
				<ul>
					<li>ドラえもんが弾を発射したとき（上キーを押したとき）。</li>
					<li>弾が星に衝突したとき。</li>
				</ul>

			</section>
			<section title="問題2：シューティングゲームにBGMをつけよう">
				<p>上の問題で効果音をつけたシューティングゲームに、今度はBGMをつけましょう。</p>
			</section>			
		</section>
		
		<section title="練習問題解答例">
			<text.turtle.applet class="ShootingGameWithSound" chapter="&CHAPTER;"/>
		</section>
	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/chapter04/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter04">
]>

<doc xml:lang='ja'>
	
	<head>
		<title>コンピュータの得意な仕事(繰り返し)</title>
	</head>
	
	<body>
	
		<section title="学習目標">
			<ul>
				<li>繰り返しのあるプログラムの実行順序を理解し、応用してプログラムが書けるようになる</li>
			</ul>
		</section>	
					
		<section title="繰り返し">		
			<p>今回のテーマは同じ命令を何度も書かずに、コンピュータに繰り返しさせることです。</p>			
			<p>繰り返しプログラムを見ていく前に、何を繰り返すか考えていきましょう。</p>
			
			<section title="何を繰り返すのか">
				<p>何回も出てきた、家のプログラムを見てみましょう。</p>			
				<text.turtle.applet class="House" chapter="&CHAPTER;"/>										
				<p>このプログラム、何度も同じことを書いている個所が2箇所ありますね。どこが同じか考えてみましょう。</p>
			</section>				
							
			<section title="繰り返しを使ったプログラム">
								
				<p>繰り返しを使って、すっきりとしたプログラムにしてみましょう。</p>
				
				<text.turtle.applet class="WhileHouse" chapter="&CHAPTER;"/>								
						
				<p>
					今回登場した"繰り返し"を使うと、プログラムを繰り返すことができます。
				</p>
				<p>
					繰り返しの一般的な形は次のとおりです。
				</p>
				<program>
while( [条件式] ) {
	処理
}
				</program>
				
				<p>条件式が成立(true)のした場合には、処理が実行されます。不成立(false)の場合は処理を飛ばします。</p>
				<p>処理が実行し終わると、もう一度条件式を評価します。</p>
				<p>これを、条件式が不成立(false)になるまで繰り返します。</p>
				<p>これをフローチャートと呼ばれる図を用いて書くと、次のようになります。</p>						
						
				<section title="プログラムのフローチャート">
					<figure 
						title="プログラムのフローチャート"
						src="image/while_flow_chart_concrete" style="scale:1.0"  />			
				</section>	
															
				<section title="繰り返しのフローチャート">
					<figure 
						title="繰り返しのフローチャート"
						src="image/while_flow_chart" style="scale:1.0"  />			
				</section>
				
				<p>
					条件式は前回の条件分岐によるプログラムで学習した書式と同じ書式が使えます。
					繰り返しを止めるために、変数を使います。この変数には、「今何回繰り返したか」といった情報を格納しておきます。
				</p>
				
			</section>
			
			<section title="繰り返しを使ったプログラムの実行過程">
								
				<p>プログラムの実行過程と変数の値の変化を見ていきましょう。</p>				
				
				<section title="変数の宣言">
					<figure 
						title="変数の宣言"
						src="image/table_model_i_01" style="scale:1.0"  />			
				</section>
								
				<section title="変数を初期化する(1を代入)">
					<figure 
						title="変数を初期化する(1を代入)"
						src="image/table_model_i_02" style="scale:1.0"  />			
				</section>	
				
				<section title="変数を評価して条件を判定する">
					<figure 
						title="変数を評価して条件を判定する"
						src="image/table_model_i_03" style="scale:1.0"  />			
				</section>			
				
				<section title="変数に1を加える">
					<figure 
						title="変数に1を加える"
						src="image/table_model_i_04" style="scale:1.0"  />			
				</section>								
				
				<p>
					変数が、5になったときに条件式が不成立(false)になるので、繰り返しが終ります。
					これで4回繰り返されるのが分かるでしょうか？
				</p>
				
			</section>			
					
		</section>
				
		<section title="応用：円を書くプログラム">		
									
			<p>
				繰り返しを使うと、円を簡単に書くことができます。次のプログラムを実行してみましょう。
			</p>
			
			<section title="円を書きつづけるプログラム">
			<text.turtle.applet class="Circle" chapter="&CHAPTER;"/>		
			</section>
			
		</section>				
		
		<section title="練習問題">
			<section title="問題1：円を描くプログラムを改良しよう">
			<p>
				最後に出てきた円を描くプログラムは、条件が無い(常に成立(true))ので止まりません。
				変数をつけ、適切な条件式を考えて、一周したらプログラムを止めるように改良して下さい。
			</p>			
			</section>
			<section title="問題2：円の描かれ方について考察しよう">			
			<p>
				一回の繰り返しで動く大きさ(fd(1))と、角度(rt(1))の数字を変更すと、円の大きさを変えることができます。
				いろいろ数字を変えて、どのようにすると自分の思った円がかけるか、考察してください。
			</p>
			<p>
				ヒント: 大きさと角度を入力できるようにすると、数字を変えるたびにコンパイルする必要がないので、いろいろ実験できますよ。
				そのようなプログラムにしてから、実験することをお奨めします。
			</p>
			</section>			
			<section title="問題3：五角形や星を繰り返しを使って描こう">
			<p>
				いままで作った五角形や星を描くプログラムを繰り返しを使って書き直してみましょう。
			</p>
			</section>
		</section>		
		
	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/chapter07/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter07">
]>

<doc xml:lang='ja'>

	<head>
		<title>たくさんのタートル</title>
	</head>

	<body>

		<section title="学習目標">
			<ul>
				<li>オブジェクトの作成と命令を行うことができる</li>
				<li>複数のオブジェクトを区別して命令を行うことができる</li>
			</ul>
		</section>

		<section title="複数のタートルを使う">
			<p>
				オブジェクトタートル編では、いままで習った制御構造を利用して、簡単なゲームやアニメーションなどのアプリケーションを作っていきたいと思います。
			</p>
			<p>
				アニメーションでは、「オブジェクト」と呼ばれるものを生成して、
				そのオブジェクトに対して命令をすることになります。
				その練習のために、まず、複数のタートルを扱ってみましょう。
			</p>

			<section title="2匹のタートルを使うプログラム">
				<p>次のプログラムを見てみましょう。</p>

				<text.turtle.applet class="TwoTurtles" chapter="&CHAPTER;"/>

				<figure
						title="2匹のタートルを使うプログラム"
						src="image/twoturtles" style="scale:1.0"  />
			</section>

			<section title="タートル（オブジェクト）の生成">
				<p>
					タートル（オブジェクト）を一匹生成するには、次のような命令文を書きます。
				</p>
				<figure
						title="タートル(オブジェクト)の生成"
						src="image/newturtle" style="scale:1.0"  />
			</section>

			<section title="タートル(オブジェクト)への命令">
				<p>
					生成されたタートル（オブジェクト）に命令するには、次のような命令文を書きます。
				</p>
				<figure
						title="タートル(オブジェクト)への命令"
						src="image/objectcommand" style="scale:1.0"  />
			</section>

			<p>
				このように、オブジェクトを生成して、
				生成したオブジェクトに対して命令を行う手法を「オブジェクト指向プログラミング」といい、
				現在のプログラミングでよく使われる手法です。
			</p>
		</section>

		<section title="同時に動いているように見せるために">

				<p>
					オブジェクトはいくつでも生成することができます。
					次のプログラムを見てみましょう。
				</p>

				<text.turtle.applet class="FourTurtles" chapter="&CHAPTER;"/>
				<p>
					このプログラムを下のプログラムと比較してみましょう。
					（同じ図形を書くのですが、動きが異なるはずです。）
				</p>

				<text.turtle.applet class="FourTurtles2" chapter="&CHAPTER;"/>

				<figure
						title="4匹のタートルを使うプログラム(1)"
						src="image/fourturtles1" style="scale:1.0"  />
				<figure
						title="4匹のタートルを使うプログラム(2)"
						src="image/fourturtles2" style="scale:1.0"  />

				<fyi title="コンピュータは同時に2度の命令をできない">
					<p>
						2つ目のプログラムでは、タートルを細かく切り替えて少しずつ動かすことによって、
						4匹のタートルが同時に動いているように見せることができます。
					</p>
					<p>コンピュータは2つの仕事を同時に行うことはできません。
					みなさんが使っているパソコンは、インターネットをやっている間にメールを見て、印刷しながらワープロも使ったりすることができます。
					これは、実は、このタートルの例のように、細かく切り替えていろいろな仕事を少しずつしているからなのです。
					</p>
				</fyi>
		</section>

		<section title="練習問題">
			<section title="問題1：たくさんのタートルで絵を描こう">
			<p>
				今まで描いた絵を、何匹かのタートルを使って、タートルの共同作業で描いてみよう。
				そのときに、全てのタートルが同時に働いているように見せよう。
				余裕があったら、仕事の遅いタートルや、仕事の速いタートルを作ることはできるか、考えてみよう。
			</p>
			</section>
		</section>

	</body>
</doc>
