=== macc704/TurtleCafe/turtlecafe2/smartdoc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from index.xml by XMLBuddy -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ELEMENT body (section+)>
<!ELEMENT console (#PCDATA)>
<!ATTLIST console title NMTOKEN #REQUIRED>
<!ELEMENT dd (#PCDATA|p)*>
<!ELEMENT dl (dd|dt)*>
<!ELEMENT doc (head,body)>
<!ATTLIST doc xml:lang NMTOKEN #REQUIRED>
<!ELEMENT dt (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT head (title)>
<!ELEMENT li (#PCDATA)>
<!ELEMENT native (#PCDATA)>
<!ATTLIST native format NMTOKEN #REQUIRED>
<!ELEMENT note (#PCDATA)>
<!ELEMENT p (#PCDATA|a|em|note|program)*>
<!ELEMENT program (#PCDATA)>
<!ATTLIST program
	encoding NMTOKEN #IMPLIED
	id NMTOKEN #IMPLIED
	javasrcSyntaxHilight NMTOKEN #IMPLIED
	normalizer CDATA #IMPLIED
	src CDATA #IMPLIED
	title NMTOKEN #IMPLIED
>
<!ELEMENT section (p|subsection|ul)*>
<!ATTLIST section title NMTOKEN #REQUIRED>
<!ATTLIST section id NMTOKEN #IMPLIED>
<!ELEMENT subsection (console|native|p|program|subsubsection|text.turtle.applet)*>
<!ATTLIST subsection title NMTOKEN #REQUIRED>
<!ELEMENT subsubsection (dl|p|program)*>
<!ATTLIST subsubsection title NMTOKEN #REQUIRED>
<!ELEMENT text.turtle.applet EMPTY>
<!ATTLIST text.turtle.applet
	chapter CDATA #REQUIRED
	class NMTOKEN #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ul (li)>

=== macc704/TurtleCafe/turtlecafe2/chapter02/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter02">
]>

<doc xml:lang='ja'>

	<head>
		<title>コンピュータに情報を記憶させてみよう（変数）</title>
	</head>

	<body>

		<section title="学習目標">
			<ul>
				<li>整数型の変数の作成（宣言），書き込み（代入），読み込み（評価と値）が使えるようになる</li>
				<li>複数の変数（変数名による区別をしつつ）が使えるようになる</li>
				<li>計算式（四則演算＋剰余計算）が使えるようになる</li>
				<li>ＣＵＩを使ってユーザ対話をするプログラムが作れるようになる</li>
			</ul>
		</section>

		<section title="変数">

			<p>今回新しく"変数"が登場します。家の大きさを変更できる次のプログラムをみてみましょう。</p>

			<section title="変数と値">
				<p>次のプログラムを見てみましょう。</p>
			<text.turtle.applet class="VariableHouse" chapter="&CHAPTER;"/>

				<p/>
				<p>変数はデータを格納しておく場所のことです。
					プログラムでは、「メモリ」の許す限り、データを格納しておくことが出来ます。
				</p>
				<p>格納する場所を一つにつき、一つの名前をつけることが出来ます。</p>
				<p>実際に格納されるデータのことを「値」といいます。</p>
				<figure
					title="変数と値"
					src="image/table_model_value" style="scale:1.0"  />
			</section>

			<section title="変数を使ったプログラムの実行">

				<p>プログラムの実行過程と変数を見ていきましょう。</p>

				<section title="変数の宣言">
					<figure
						title="変数の宣言"
						src="image/table_model_x_01" style="scale:1.0"  />
				</section>

				<section title="変数へ値を代入する">
					<figure
						title="変数へ値を代入する"
						src="image/table_model_x_02" style="scale:1.0"  />
				</section>

				<section title="変数を評価して値にする">
					<figure
						title="変数を評価して値にする"
						src="image/table_model_x_03" style="scale:1.0"  />
				</section>

			</section>

			<section title="複数の変数と変数名">
				<p>変数はいくつでも使うことが出来ます。</p>
				<p>
					区別するために、変数には異なる名前をつけなければなりません。
					異なる名前ならば好きな名前をつけることが出来ます。
					空白や特殊記号が使えないのはクラス名と同じです。
				</p>

				<section title="複数の変数と変数名">
					<text.turtle.applet class="MultiVariableHouse" chapter="&CHAPTER;"/>
				</section>

				<section title="プログラムの実行過程">
					<p>プログラムの実行過程を追ってみましょう。</p>
					<figure
						title="変数の宣言"
						src="image/table_model_name_01" style="scale:1.0"  />
					<figure
						title="変数の宣言"
						src="image/table_model_name_02" style="scale:1.0"  />
					<figure
						title="変数への値の代入"
						src="image/table_model_name_03" style="scale:1.0"  />
					<figure
						title="変数への値の代入"
						src="image/table_model_name_04" style="scale:1.0"  />
					<figure
						title="変数を評価して値にする"
						src="image/table_model_name_05" style="scale:1.0"  />
				</section>

			</section>
		</section>

		<section title="コンピュータに計算をさせる">

			<section title="計算式を使ったプログラム">
				<text.turtle.applet class="DoubleHouse" chapter="&CHAPTER;"/>
				<p>
					コンピュータは計算機ですから、計算をさせることが出来ます。例えば、次のように書くと</p>
				<program>
rightAngle * 2
				</program>
				<p>掛け算を行うことが出来ます。</p>
				<p>このような、計算を行う書法のことを「式」といいます。</p>

				<p>Javaで使うことが出来る基本的な計算命令を以下に示します。</p>
				<dl>
					<dt>+</dt>
					<dd>足し算をします</dd>
					<dt>-</dt>
					<dd>引き算をします</dd>
					<dt>*</dt>
					<dd>掛け算をします</dd>
					<dt>/</dt>
					<dd>割り算をします</dd>
					<dt>%</dt>
					<dd>割り算の余りを求めます</dd>
				</dl>
			</section>

			<section title="計算式を使ったプログラムの実行">

				<p>次のように評価（計算）されて、具体的な値になり、プログラムが動きます。</p>
				<figure
					title="変数の宣言"
					src="image/table_model_expression_01" style="scale:1.0"  />
			</section>

			<section title="計算式と代入文を使ったプログラムの実行">

				<p>計算式があっても、右辺から評価されるのは一緒です。</p>
				<figure
					title="変数の宣言"
					src="image/table_model_expression_02" style="scale:1.0"  />
				<fyi title="考えてみよう">
					次のようなプログラムが動かない（コンパイルエラーとなる）のは何故ですか？
					考えてみましょう。
				<program>
length / 2  = smallHouseLength;
				</program>
				</fyi>
			</section>

		</section>

		<section title="ユーザと対話する（インタラクティブ）なプログラム">

			<section title="入力を受け付ける">
				<text.turtle.applet class="InputHouse" chapter="&CHAPTER;"/>


			<p>入力を受け付けるには、</p>
			<program>
input()
			</program>
			<p>命令を使います。</p>
			<p>評価すると、ユーザが入力した値になります。そして、その値が変数に代入されます。</p>

			</section>

			<section title="ユーザにメッセージを出す">
				<text.turtle.applet class="PromptHouse" chapter="&CHAPTER;"/>


			<p>ユーザにメッセージを出すには</p>
			<program>
print("ここに出したいメッセージを書く")
			</program>
			<p>命令を使います。</p>
			<p>出したいメッセージを「"」（ダブルクォーテーション）で囲んでください。</p>

			</section>

		</section>

		<section title="おみくじ">
				<section title="乱数">
				<text.turtle.applet class="RandomHouse" chapter="&CHAPTER;"/>

			<p>乱数値を（命令毎に毎回変わる値）に取得するには</p>
			<program>
random(数)
			</program>
			<p>命令を使います。</p>
			<p>実行されるごとに異なる値が自動的に選択されます。</p>
			<p>「０」から「数の所に書いた数」未満のどれかの数字が選択されます。</p>
			<p>（例：random(10)のとき、0から9までの１０種類のどれかの数が選択されます）</p>
			</section>
		</section>

		<section title="練習問題">
			<section title="問題1：与えられた大きさの正五角形を描くプログラム">
			<p>
				ユーザの入力を受け取り、その長さを一辺の長さとして正五角形を描くプログラムを作ってください。
			</p>
			</section>
			
			<section title="問題2：乱数を使って星を描くプログラム">
			<p>
				長さに乱数を使い、実行するたびに大きさが変わる星を描くプログラムを作ってください。
				乱数は50以上100未満の間になるようにすること。
			</p>
			</section>
		</section>

	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/chapter08/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter08">
]>

<doc xml:lang='ja'>

	<head>
		<title>アニメーション入門（いままで作ったものを動かそう）</title>
	</head>

	<body>

		<section title="学習目標">
			<ul>
				<li>アニメーションの基本構造を理解して、今までつくったオブジェクトを動かすことができるようになる</li>
				<li>タートルの座標系や拡大縮小命令を理解して、自在にオブジェクトを移動させることができる</li>
			</ul>
		</section>

		<section title="アニメーションの基本">

			<p>
				ここからはオブジェクト指向プログラミングを使って、アニメーションを作っていきたいと思います。
			</p>

			<section title="回る家">
				<p>
					まず、下のプログラムを実行してみましょう。
				</p>

				<text.turtle.applet class="RotateHouse" chapter="&CHAPTER;"/>

				<p>
					ここでは、Houseのプログラムオブジェクトとして生成しています。
					つまり、<em>いままでタートルで作った絵を使うことができる</em>のです。
				</p>
				<p>
					タートルを使って自分の作ったオブジェクトを生成するには、次のような命令文を書きます。
				</p>
				<figure
						title="オブジェクトの生成"
						src="image/newobject" style="scale:1.0"  />

				<fyi title="使うオブジェクトを書くプログラムは同じフォルダに置く">
					<p>
						例えば、RotateHouse.javaアニメーションで、House.javaを使う場合は、
						その2つを同じフォルダに置く必要があります。
					</p>
					<p>
						同じフォルダに置いていないとコンパイルエラーが出るので注意してください。
					</p>
				</fyi>
			</section>

			<section title="アニメーションの基本構造">
				<p>
					RotateHouse.javaをもう一度よく見てみましょう。
					特に、
				</p>
				<program>
while(true){
	//待つ

	//処理

	//再描画
}
				</program>
				<p>
					ここの部分が、今までと異なる所で、アニメーションをするプログラムの特徴です。
					どのようなアニメーションをするプログラムでも基本構造は同じです。
					図解すると下のようになります。
				</p>
				<figure
						title="アニメーションプログラムの構造"
						src="image/animationmodel" style="scale:1.0"  />
				<figure
						title="アニメーションプログラムの構造(具体的)"
						src="image/animationmodelconcrete" style="scale:1.0"  />

				<p>
					ちなみに、House.javaは次のようなプログラムでした。
				</p>
				<text.turtle.applet class="House" chapter="&CHAPTER;"/>

			</section>

			<section title="アニメーションをするための新しい命令">
				<dl>
					<dt>sleep([秒の指定])</dt>
					<dd>指定された秒数だけ、眠り（止まり）ます。 1を入れれば1秒止まり、0.1入れれば0.1秒止まります。</dd>
					<dt>update()</dt>
					<dd>
						画面を書き換えます。画面を書き換えないと、fd(5)などで移動しても、
						画面は書き換わらない（動かない）ので注意してください。
					</dd>
				</dl>

				<fyi title="何秒眠るか">
					<p>
						sleep()命令の中の数字を小さくすることによって、アニメーションを早くすることができます。
						しかし、コンピュータの能力にも限界があります。
						軽いアニメーションならば0.01秒（秒間100コマ）ぐらいまでならなんとか動きますが、
						画像などを使うといくら小さい値を入れても、コンピュータの計算が追いつかなくなります。
					</p>

					<p>
						人間が目に分かるのは、秒間30コマまでといわれています（テレビがそれぐらいです）ので、
						それぐらいを目安に数値を決めると良いでしょう。
					</p>
				</fyi>
			</section>

			<section title="円を描く家">

				<p>
					オブジェクトになっても、基本的なタートルの命令はどれでも使うことができます。
					次のプログラムは、円を描く家のプログラムです。
				</p>

				<text.turtle.applet class="CircleHouse" chapter="&CHAPTER;"/>

				<p>
					down() 命令で、ペンを下ろして軌跡が描かれるようになっています。
				</p>

				<figure
					title="円を描く家"
					src="image/circlehouse" style="scale:1.0"  />

				<fyi title="初期値">
					<p>
						いままでのタートルでは、down()命令をしなくても、
						最初はペンを下ろした状態から始まっていました。
					</p>

					<p>
						しかし、アニメーションでは、軌跡は要らないことが多いので、
						初期値がペンを上げた状態になっています。
					</p>

					<p>
						プログラムを書くときには、"最初の状態"を意識する必要があります。
						これを「初期値」や「デフォルト値」といいます。
					</p>
				</fyi>

			</section>
		</section>

		<section title="座標の制御">
			<section title="上向きのまま右に動かす">
				<p>
					次に示すのは、家が右に動いていくプログラムです。
				</p>
				<text.turtle.applet class="MoveRightHouse1" chapter="&CHAPTER;"/>
				<p>
					今までの方法では、前か後ろにしか進めませんが、
					家は上向きのまま、右に動かしたい場合があります。
				</p>
				<p>
					いままでの方法でも、下のように工夫することによって目的は達成できますが、
					ここでは、warp命令を使ったエレガントな解決方法を考えます。
				</p>
				<text.turtle.applet class="MoveRightHouse2" chapter="&CHAPTER;"/>
			</section>

			<section title="ワープを使う">
				<p>
					warp命令を使うと、回転せずに、好きな所にオブジェクトを移動することができます。
				</p>

				<text.turtle.applet class="WarpHouse" chapter="&CHAPTER;"/>

				<p>
					このプログラムの実行結果は以下のようになります。
				</p>
				<figure
					title="WarpHouse.javaの実行結果"
					src="image/warphouse" style="scale:1.0"  />

				<fyi title="座標に関する新しい命令">
					<dl>
						<dt>warp([x座標, y座標])</dt>
						<dd>
							指定されたx座標, y座標の位置に、そのオブジェクトをワープ（瞬間的に移動）させます。
							命令に数字2つ必要なので、カンマで区切るのを忘れずに。
						</dd>
						<dt>getX()</dt>
						<dd>
							現在のx座標を取得します。
						</dd>
						<dt>getY()</dt>
						<dd>
							現在のy座標を取得します。
						</dd>
					</dl>
				</fyi>

				<p>
					ちなみに、一般にコンピュータ環境では、数学とはちょっと違った座標体系が使われます。
					タートルの場合もそうです。以下のようになっているので気をつけてください。
				</p>

				<figure
					title="タートルの座標体系"
					src="image/coordinates" style="scale:1.0"  />

				<p>
					さあ、ワープを使って、家を右に移動しましょう。
				</p>
				<text.turtle.applet class="MoveRightHouse3" chapter="&CHAPTER;"/>
				<p>
					さらに、右端までいったら左端にワープするように改造します。
				</p>
				<text.turtle.applet class="MoveRightHouse4" chapter="&CHAPTER;"/>

				<p>だんだんアニメーションらしくなってきました。</p>

			</section>
		</section>

		<section title="大きさの変更(拡大/縮小)">
			<section title="大きさを変更するプログラム">
				<p>
					オブジェクトは、大きさを変更することもできます。
				</p>
				<text.turtle.applet class="LargeHouse" chapter="&CHAPTER;"/>
				<fyi title="大きさに関する新しい命令">
					<dl>
						<dt>size([横の長さ], [縦の長さ])</dt>
						<dd>
							そのオブジェクトを横の長さと縦の長さを、指定された大きさにします。
							命令に数字2つ必要なので、カンマで区切るのを忘れずに。
						</dd>
						<dt>getWidth()</dt>
						<dd>
							現在の横幅を取得します。
						</dd>
						<dt>getHeight()</dt>
						<dd>
							現在の縦幅を取得します。
						</dd>
					</dl>
				</fyi>
			</section>

			<section title="徐々に大きくする">
				<p>
					アニメーションループをうまく利用すれば、徐々に大きくなっていくプログラムが書けます。
				</p>
				<text.turtle.applet class="LargerHouse" chapter="&CHAPTER;"/>
				<p>
					大きくなりすぎたら、小さく戻してあげましょう。
				</p>
				<text.turtle.applet class="LargerHouse2" chapter="&CHAPTER;"/>

				<fyi title="大きさ変更に便利な命令">
					<dl>
						<dt>scale([倍率])</dt>
						<dd>
							そのオブジェクトを指定された倍率の大きさにします。
						</dd>
						<dt>large([長さ])</dt>
						<dd>
							指定した長さだけ縦横を幅を大きくします。
						</dd>
						<dt>small([長さ])</dt>
						<dd>
							指定した長さだけ縦横の幅を小さくします。
						</dd>
						<dt>wide([長さ])</dt>
						<dd>
							指定した長さだけ横幅を大きくします。
						</dd>
						<dt>narrow([長さ])</dt>
						<dd>
							指定した長さだけ横幅を小さくします。
						</dd>
						<dt>tall([長さ])</dt>
						<dd>
							指定した長さだけ縦幅を大きくします。
						</dd>
						<dt>little([長さ])</dt>
						<dd>
							指定した長さだけ縦幅を小さくします。
						</dd>
					</dl>
				</fyi>
			</section>
		</section>

		<section title="練習問題">
			<section title="流れ星アニメーションを作ろう">
			<p>
				星を書くプログラム(Star.java)を使って、流れ星のプログラムを書いてみて下さい。
			</p>

			<p>ダウンロードはこちらから</p>
			<ul>
				<li><a href="../html4/&CHAPTER;/src/Star.java">Star.java</a></li>
			</ul>

			<p>流れ星は、次の手順で進めていくとうまくできます。</p>
			<ol>
				<li>Star.javaをダウンロードして動かしてみる</li>
				<li>ShootingStar.javaを新しく作る(Star.javaは変更しないこと)</li>
				<li>ShootingStar.javaに、Starオブジェクトを生成して表示するプログラムを書く</li>
				<li>星を回してみる</li>
				<li>座標を使って、星を右に動かしてみる</li>
				<li>一番右端にいったら、左端に戻るようにする</li>
				<li>星を下にも動かす</li>
				<li>一番下にいったら、上に戻るようにする</li>
				<li>星の大きさを変える</li>
				<li>星を増やす</li>
			</ol>
			</section>
		</section>
	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/chapter10/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter10">
]>

<doc xml:lang='ja'>

	<head>
		<title>ゲームを作ろう！</title>
	</head>

	<body>

		<section title="学習目標">
			<ul>
				<li>キーボード、マウスを使ってユーザと対話するプログラムを作れるようになる</li>
				<li>オブジェクト同士の当たり判定を取得し、オブジェクトが連携して動作するプログラムを作れるようになる</li>
			</ul>
		</section>

		<section title="キーボード入力の判定">

			<section title="キーコードの取得">

			<p>
				key()命令を使うと、いま押されているキーボードの番号（キーコード）を
				調べることができます。
			</p>
			<p>
				次のプログラムは、車がキーにあわせて、上下左右に動くプログラムです。
			</p>
			<text.turtle.applet class="HandleKey" chapter="&CHAPTER;"/>
				<fyi title="キー入力を受け取る新しい命令">
					<dl>
						<dt>key()</dt>
						<dd>
							<p>
								いま押されているキーボードの番号（キーコード）を調べることができます。
							</p>
							<p>
								何も押されていない時は、キーコードが -1 になります。
							</p>
						</dd>
					</dl>
				</fyi>

			</section>

			<section title="キーコードを調べる">
			<p>
				キーボードのキーに対応するキーコードを調べるには、
				次のプログラムを使うと良いでしょう。
			</p>
			<text.turtle.applet class="CheckKeycode" chapter="&CHAPTER;"/>
			</section>
		</section>

		<section title="マウス入力の判定">

			<section title="マウスの位置を調べる">

			<p>
				mouseX()、mouseY() 命令を使うと，
				マウスが今どこにいるのかを調べることができます。
			</p>
			<p>下のプログラムは、マウスの位置に車が移動するプログラムです。</p>
			<text.turtle.applet class="HandleMouse" chapter="&CHAPTER;"/>
				<fyi title="マウスの位置を調べる新しい命令">
					<dl>
						<dt>mouseX()</dt>
						<dd>
							<p>
								マウスのx座標を取得します。
							</p>
						</dd>
						<dt>mouseY()</dt>
						<dd>
							<p>
								マウスのy座標を取得します。
							</p>
						</dd>
					</dl>
				</fyi>
			<p>
				x()、y()、mouseX()、mouseY()命令で取得した座標は，
				わざわざ変数に入れなくても、そのまま他の命令で使う値として使うこともできます。
			</p>

			<text.turtle.applet class="HandleMouse2" chapter="&CHAPTER;"/>
			</section>

			<section title="マウスが押されているかどうか調べる">

			<p>
				mouseDown()命令を使うと、マウスが押されているか調べることができます。
				mouseX()、mouseY() 命令と組み合わせて使うと、どこで押されているかも調べられます。
			</p>
			<p>下のプログラムは、マウスをクリックした所に車が移動するプログラムです。</p>
			<text.turtle.applet class="HandleMouse3" chapter="&CHAPTER;"/>

				<fyi title="マウス入力を調べる新しい命令">
					<dl>
						<dt>mouseDown()</dt>
						<dd>
							<p>
								いまマウスが押されているかどうかを調べます。
								必ず、if文の条件文の中に書いて下さい。
							</p>
						</dd>
					</dl>
				</fyi>

			</section>

			<section title="マウス入力を詳しく調べる">

			<p>
				マウスボタンの左右や、ダブルクリックを調べる場合は，
				次のようなプログラムを書きます。
			</p>

			<text.turtle.applet class="HandleMouse4" chapter="&CHAPTER;"/>

				<fyi title="マウス入力を詳しく調べる新しい命令">
					<dl>
						<dt>leftMouseDown()</dt>
						<dd>
							<p>
								いまマウスの左ボタンが押されているかどうかを調べます。
								必ず、if文の条件文の中に書いて下さい。
							</p>
						</dd>
						<dt>rightMouseDown()</dt>
						<dd>
							<p>
								いまマウスの右ボタンが押されているかどうかを調べます。
								必ず、if文の条件文の中に書いて下さい。
							</p>
						</dd>
						<dt>doubleClick()</dt>
						<dd>
							<p>
								マウスがダブルクリックされたかどうかを調べます。
								必ず、if文の条件文の中に書いて下さい。
							</p>
						</dd>
					</dl>
				</fyi>
			</section>
		</section>

		<section title="あたり判定">

			<section title="２つのオブジェクトのあたり判定">

			<p>
				intersects()命令を使うと、2つのオブジェクトが当たっているかどうか、
				調べることができます。
			</p>
			<p>
				下のプログラムは、車がドラえもんに当たると、ドラえもんが小さくなるプログラムです（マウスで車を動かせます）。
			</p>

			<text.turtle.applet class="IntersectsJudge" chapter="&CHAPTER;"/>
				<fyi title="あたり判定に関する新しい命令">
					<dl>
						<dt>intersects([判定相手のオブジェクト])</dt>
						<dd>
							オブジェクトが、指定された判定相手のオブジェクトと当たっているかどうか調べます。
							必ず、if文の条件文の中に書いて下さい。
						</dd>
					</dl>
				</fyi>
			</section>

			<section title="座標とオブジェクトのあたり判定">

			<p>
				2つのオブジェクトのあたり判定でなく、マウスの位置が、オブジェクトと当たっているか判定したい時があります。
			</p>
			<p>
				下のプログラムは、マウスが車の上に来る（マウスの座標が車の領域に含まれる）と、車が小さくなるプログラムです。
			</p>

			<text.turtle.applet class="ContainsJudge" chapter="&CHAPTER;"/>
				<fyi title="座標とオブジェクトのあたり判定に関する新しい命令">
					<dl>
						<dt>contains([x座標], [y座標])</dt>
						<dd>
							オブジェクトが指定された座標内に含まれているかどうか調べます。
							必ず、if文の条件文の中に書いて下さい。
						</dd>
					</dl>
				</fyi>
			</section>

		</section>

		<section title="課題">
			<section title="簡単なゲームを作ろう">
			<p>
				これで，このテキストの内容はすべておしまいです。
				ここまでの内容を駆使して、面白いソフトウエアを作ってくださることを期待します。
			</p>
			<fyi title="やってみよう！">
			<p>
				プレイヤーの画像を用意し、キーボードの矢印（↑→←↓）キーを使って、プレイヤーを上下左右に操作するプログラムを作りましょう。
			</p>
			<p>
				プレイヤーの画像は、ネットのフリー素材集などから好みのものを探し、ダウンロードして使ってください。
			</p>
			</fyi>
			<fyi title="やってみよう！">
			<p>
				アイテム（<a href="#sec:imageturtle">画像タートル</a>）と得点板（<a href="#sec:textturtle">テキストタートル</a>）をつくり、プレイヤーを操作してアイテムを取る（アイテムに触れる）と得点が増えるプログラムを作りましょう。
			</p>
			<p>
				アイテムの画像は、ネットのフリー素材集などから好みのものを探し、ダウンロードして使ってください。
			</p>
			</fyi>
			<fyi title="やってみよう！">
			<p>
				自由な発想で、簡単なオリジナルゲームを作りましょう。
			</p>
			</fyi>
			<p>
				最後に、シューティングゲームのサンプルプログラムを贈ります。操作方法はプログラムを読めばわかります。GOOD LUCK!
			</p>
			<text.turtle.applet class="ShootingGame" chapter="&CHAPTER;"/>
			</section>
		</section>

	</body>
</doc>

=== macc704/TurtleCafe/turtlecafe2/chapter01/index.xml
<?xml version='1.0' encoding='Shift_JIS' ?>

<!DOCTYPE doc SYSTEM "../smartdoc.dtd"[
<!ENTITY CHAPTER "chapter01">
]>

<doc xml:lang='ja'>
	<head>
		<title>はじめてのJavaタートルプログラミング</title>
	</head>

	<body>

		<section title="学習目標">
			<p>
				<ul>
					<li>タートルの基本的な命令を使いこなし、タートルで図形が描けるようになる</li>
				</ul>
			</p>
		</section>

		<section title="最初のプログラムの解説">
			<p>導入編の「サンプルプログラムの使い方」で動かした家を描くサンプルプログラムを解説します。</p>

			<section title="家を書くサンプルプログラム">
				<p>下に、導入編で動かした家を描くサンプルプログラムを示します。</p>

				<text.turtle.applet class="House" chapter="&CHAPTER;" />
			</section>

			<section title="プログラムの要素" id="elements">

				<section title="ブロック">
					<p>
						中括弧で囲まれた部分をブロックと呼びます。 Javaプログラムは複数のブロックから構成されます。
						ブロックの中にブロックを入れることも出来ます。
					</p>
				</section>

				<section title="クラス" id="class">
					<p>
						Javaプログラムの一つの単位をクラスと呼びます。
						本格的なプログラムでは、クラスが複数になりますが、しばらくは一つだけです。
					</p>
					<p>
						クラスを作るための先頭行は、
						<program>
<![CDATA[6: public class [クラス名] extends Turtle{]]>
						</program>
						となる。この行の最後の括弧から、対応する括弧（ファイルの一番最後にある括弧）までがクラスブロックです。
						Javaのプログラムは全てクラスブロックの中に書かれます。
					</p>

					<p>
						クラス名は自由に決められますが、気をつけてほしいのは、
						ファイル名はクラス名に「.java」をつけたものにすることです。
						（例えば、クラス名がHouseならファイル名はHouse.javaにする必要がある)
						論プロエディタでは自動でクラス名とファイル名をそろえてくれるので、考えなくてOKです。
					</p>

				</section>

				<section title="メソッド">

					<program>
<![CDATA[  14: 	void [メソッド名](){]]>
					</program>

					<p>
						から始まるブロックをメソッドブロックといいます。
						Javaのプログラムの命令は、全てメソッドブロックの中に書かれます。
						メソッドは、命令をまとめて一つに束ねたもの、ということもできます。
					</p>
					<p>
						メソッドブロックはクラスブロックの中に書く必要があります。
						タートルプログラムは、startという名前のメソッドを最初に実行しようとします。だから、タートルで作る一つ目のメソッド名はstartでなければなりません。
					</p>
					<p>
						しばらくすると、複数のメソッドを扱いますが、現時点では、
						プログラムはstart()の中括弧の中に書く、と覚えておけばよいでしょう。
					</p>
				</section>

				<section title="命令">
					<p>
						startメソッドブロックの中にある、rt(30)やfd(60)がタートルに指示する命令です。
					</p>
					<p>
						メソッド内に書かれた命令は、
						<em>必ず上から順番に実行されます。</em>
					</p>
					<p>以下にタートルに指示できる命令の一覧を示します。</p>
					<dl>
						<dt>rt([角度の指定])</dt>
						<dd>タートルを指定した角度だけ右に回す</dd>

						<dt>lt([角度の指定])</dt>
						<dd>タートルを指定した角度だけ左に回す</dd>

						<dt>fd([長さの指定])</dt>
						<dd>タートルを指定した長さだけ進める</dd>

						<dt>bk([長さの指定)</dt>
						<dd>タートルを指定した長さだけ後ろに進める</dd>

						<dt>up()</dt>
						<dd>タートルがペンを上げる(軌跡がかかれなくなる)。</dd>

						<dt>down()</dt>
						<dd>タートルがペンを下げる(軌跡がかかれるようになる)。</dd>

						<dt>color([色の指定])</dt>
						<dd>
							<p>
								ペンの色を変える
								<note>
									赤なら、color(java.awt.Color.red)。青なら、color(java.awt.Color.blue)のように指定する。
								</note>
							</p>
						</dd>
					</dl>
				</section>

				<section title="命令の区切り">
					<p>
						Javaのプログラムでは命令と命令の区切りに必ず「;」（セミコロン）を入れる必要があります。
						これを入れないと、コンピュータがどこで命令が区切られているのか、理解することができません。
					</p>
					<p>ちなみに、セミコロンが入っていれば、複数の命令を次のように同じ行に書いてもＯＫです。</p>
					<program>lt(30); fd(50);</program>
				</section>


				<section title="コメント">
					<p>
						コメントはプログラム（命令）としては考慮されず、読み飛ばされます。
						しかし、人間が読めないとメンテナンスにこまるためにコメントをつけておきます。ファイルの先頭には、プログラムのタイトル、名前や日付を忘れずに。
					</p>
					<dl>
						<dt>範囲指定コメント</dt>
						<dd>「/*」から「*/」までコメントになります</dd>

						<dt>行コメント</dt>
						<dd>「//」から先行の終わりまでコメントになります</dd>
					</dl>
				</section>

			</section>
		</section>

		<section title="プログラムの作成手順">

			<section title="ファイルの作成">
				<p>
					論プロエディタの「File」メニューから「NewFile(Class）」を選び、
					テンプレートは「Turtle」を選んでください。
				</p>
			</section>

			<section title="プログラムの書き方">
				<p>
					「タートルを動かす処理」の「 { 」と「 } 」の間に、タートル命令（rt(90)やfd(100)など）を書いてください。
				</p>
			</section>

		</section>

		<section title="プログラムミスと対処" id="programmiss">

			<section title="コンパイルエラー" id="compileerror">
				<p>プログラムの書きかたを間違えると、コンパイルしたときにエラーになります。</p>
				<p>例えば、コマンドの区切りでセミコロンを忘れると、次のようなエラーがでます。</p>
				<console title="コンパイルエラー">
>javac House.java House.java:13: ';' がありません。 rt(120)
^ エラー 1 個 >
				</console>
				<p>
					コンパイルエラーがでたら、実行することはできないので、ソースを直して、再コンパイルするしかありません。
					どうしても原因が分からない時は、ＴＡなどに相談してください。
				</p>
			</section>

			<section title="バグ">
				<p>
					コンパイルが正常に通っても、プログラムが間違っていて、意図した通りに動作しないことをバグといいます。
					コンピュータは、必ず
					<em>命令した通りに動作します。</em>
				</p>
				<p>バグがあったら、修正しましょう。バグを修正することをデバッグといいます。</p>
				<p>
					プロでも、最初から意図したプログラムを書くのは難しいものです。
					プログラム上達の早道は、一発で動かそうとせずに、
					早くバグを見つけて、修正できるようになるようになるように心がけることです。
				</p>
			</section>
		</section>

		<section title="タートルを使って好きな図形を書くためのテクニック">
			<section title="曲線が書きたい">
				<p>
					コンピュータで本当の曲線は書けませんが、それらしく見せることはできます。
					次のプログラムを見てみましょう。
				</p>
				<text.turtle.applet class="Curve" chapter="&CHAPTER;" />

				<p>5度曲がり、5歩進むことを繰り返しています。</p>

				<fyi title ="やってみよう">
				<p>長さと角度を調整して、もっと精密な曲線に近づけてみよう。</p>
				</fyi>

				<p>
					実はコンピュータで、"本物"の曲線を書くことはできません。
					しかし、上記のように"擬似的"に表現することで、人間の目をごまかすことはできます。
					このように擬似的に表現することを「ディジタル」表現といいます。これに対して、紙に書くような本物の曲線を「アナログ」表現といいます。
				</p>
			</section>

			<section title="タートルの最初の位置を変えたい">
				<p>
					教育上の理由から、初期位置を変える機能は搭載していません。
					最初の位置を変えたいときは、ペンをあげて、好みの位置まで移動するプログラムを書く必要があります。
					ちなみに、タートルは最初(100, 100)の座標で、上向きになっています。
				</p>
			</section>
		</section>

		<section title="練習問題">
			<section title="問題1：正五角形描こう">
				<p>
					進める（fd）命令や、回す（rt）命令を使って、正五角形を描くプログラムを作りましょう。
				</p>
				<figure
						title="正五角形"
						src="image/pentagon" style="scale:1.0"  />
			</section>
			<section title="問題2：星を描こう">
				<p>
					進める（fd）命令や、回す（rt）命令を使って、星を描くプログラムを作りましょう。
				</p>
				<figure
						title="星"
						src="image/star" style="scale:1.0"  />
			</section>
			<section title="問題3：好きな図形を描こう">
				<p>タートルを使って、好きな絵を描くプログラムを作りましょう。</p>
				<p>Squeakテキストに載っている図形などを描いてみましょう。（Squeakテキストに載っている図形は<a href="http://www.crew.sfc.keio.ac.jp/squeak/text/htmlver_text/index_p2_c3.html#doc5_3208">こちら</a>）</p>
			</section>
		</section>

	</body>
</doc>
